spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    default-schema: liquibase_service

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: dbo

jwt:
  secret: bc2dfaba0bf4d1ae1b36f9e03f364c6f02cee9698315d2ed866b36e6abf70e03
  expiration: 144000000