spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: bc2dfaba0bf4d1ae1b36f9e03f364c6f02cee9698315d2ed866b36e6abf70e03
  expiration: 144000000